INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (101,'SATHYA','G','SATHYA.G@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (201,'OMKAR','G','OMKAR.G@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (301,'SATHYA','K','SATHYA.K@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (401,'OMKAR','S','OMKAR.S@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (501,'SATHYA','P','SATHYA.P@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (601,'OMKAR','Z','OMKAR.Z@MYMAIL.COM');

INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (701,'A','G','A.G@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (702,'B','G','B.G@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (703,'C','K','C.K@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (801,'D','S','D.S@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (802,'E','P','E.P@MYMAIL.COM');
INSERT INTO EMPLOYEE(ID,FIRST_NAME,LAST_NAME,EMAIL) VALUES (901,'F','Z','F.Z@MYMAIL.COM');